### ISSUE TITLE
A bit slow when fuzzying finding

### ISSUE THREAD

**Issue by joshpetit** [akirak/ivy-omni-org#5]
Hey! Awesome package, but a problem I've had is that when searching within the list of files it's exceptionally slow, not sure what may be causing this, here's my config:

```lisp
(use-package ivy-omni-org
             :config
             (setq ivy-omni-org-file-sources '(org-agenda-files))
             )
```

**Comment by akirak** [comment]
Nowadays I don't use this package. I wrote it when I was not as proficient in Emacs Lisp as I am now, so it can be slow, but I'm not sure what the cause is. 

Unless you have a specific reason for using this package, I'd recommend you use `consult`, `marginalia`, and `embark` for a similar purpose.

If you are still interested in this package, please answer the following questions:

- How many files do you have in `org-agenda-files`? 
- How many open Org buffers do you have?

Also running a profiler (`M-x profiler-start`) may help me investigate the issue.

**Comment by joshpetit** [comment]
Thanks for following up, I'm just now learning how to configure emacs and I ended up just using consult and passing it the directory where I store my agenda files, thank you though!
